# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170606_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btleevent',
            options={'ordering': ('arrivalTime',), 'verbose_name_plural': 'btleevents'},
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='access_address',
            new_name='accessAddress',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='advertising_address',
            new_name='advertisingAddress',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='advertising_header',
            new_name='advertisingHeader',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='arrival_time',
            new_name='arrivalTime',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='data',
            new_name='btleData',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='cap_length',
            new_name='capLength',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='epoch_time',
            new_name='epochTime',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='highest_layer',
            new_name='highestLayer',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppi_dlt',
            new_name='ppiDlt',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppi_flags',
            new_name='ppiFlags',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppi_header_length',
            new_name='ppiHeaderLength',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppi_reserved',
            new_name='ppiReserved',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppi_version',
            new_name='ppiVersion',
        ),
    ]
