# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170606_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btleevent',
            options={'ordering': ('arrivaltime',), 'verbose_name_plural': 'btleevents'},
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='accessAddress',
            new_name='accessaddress',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='advertisingAddress',
            new_name='advertisingaddress',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='advertisingHeader',
            new_name='advertisingheader',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='arrivalTime',
            new_name='arrivaltime',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='btleData',
            new_name='btledata',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='capLength',
            new_name='caplength',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='epochTime',
            new_name='epochtime',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='highestLayer',
            new_name='highestlayer',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppiDlt',
            new_name='ppidlt',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppiFlags',
            new_name='ppiflags',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppiHeaderLength',
            new_name='ppiheaderlength',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppiReserved',
            new_name='ppireserved',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppiVersion',
            new_name='ppiversion',
        ),
    ]
