# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170606_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='btleevent',
            name='domain',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
