# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_btleevent_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btleevent',
            old_name='accessaddress',
            new_name='advertisingdata',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppireserved',
            new_name='advertisingtype',
        ),
        migrations.RenameField(
            model_name='btleevent',
            old_name='ppiversion',
            new_name='btletype',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='caplength',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='epochtime',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='highestlayer',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='layers',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='ppidlt',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='ppiflags',
        ),
        migrations.RemoveField(
            model_name='btleevent',
            name='ppiheaderlength',
        ),
        migrations.AddField(
            model_name='btleevent',
            name='channelindex',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='btleevent',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='btleevent',
            name='companydata',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
