# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_androidevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clocktimedifference',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='run',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
