# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180113_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btleevent',
            name='run',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
