# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180113_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='size',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
