# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-07 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_event_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='domainVal',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
