# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='celsius',
            field=models.CharField(max_length=1000),
        ),
    ]
